menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/boazabramson'}
- {icon: 'twitter', link: 'https://twitter.com/Boaz_Abramson'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/boaz-abramson-27b28b133/'}

contacts:
- {name: 'Boaz Abramson', title: 'Assistant Professor', department: 'Finance', institution: 'Columbia Business School', institution_address: '665 West 130th Street, New York, NY 10027', phone: '(650) 2506-287', email: 'ba2695@gsb.columbia.edu', office: '723  Kravis', image: 'assets/img/contact.jpg'}
